#!/bin/sh
# badge-patch.sh - show the Visionary badge on this self-hosted instance.
#
# The web client hides self-hosted-only bits of the profile badges. From
# src/features/user/components/popouts/UserProfileBadges.tsx (2026-10 releases):
#
#   const selfHosted = RuntimeConfig.isSelfHosted();
#   ...
#   if (!selfHosted && profile.premiumType === UserPremiumTypes.LIFETIME) {
#           tooltipText = "Fluxer Visionary since ..."; badgeUrl = helpArticle('visionary');
#   } else if (profile.premiumSince) { tooltipText = "... subscriber since ..."; }
#   ...
#   if (!selfHosted && profile.premiumType === UserPremiumTypes.LIFETIME
#           && profile.premiumLifetimeSequence != null) {
#           result.push({type: 'text', key: 'visionary_id', text: `#${sequence}`, ...});
#
# The Plutonium badge itself is no longer gated: it shows whenever the instance
# reports premium_enabled (premium mode 'mirror'). Earlier releases gated the whole
# premium badge instead (`!selfHosted && profile?.premiumType && ...`); that gate is
# still removed if a bundle has it. So this deletes `!selfHosted` from each of those
# conditions, and a lifetime account shows "Visionary since" and "Visionary ID #n"
# exactly as on fluxer.app. All gates are client-side only: the API serves
# premium_type, premium_since and premium_lifetime_sequence to profile viewers on any
# instance (UserAccountLookupService strips them only for BADGE_HIDDEN or a restricted
# profile). The STAFF badge has no such gate.
#
# There is no environment variable for this, and flipping FLUXER_SELF_HOSTED would
# change the setup flow, registration and the Stripe paths too. So this patches the
# shipped bundle: take the chunk out of the app-proxy image, edit it, and serve it
# back through docker-compose.override.yml. The image is never modified, and
# `badge-patch.sh --revert` puts everything back.
#
# The patched chunk is published under a NEW, content-derived name
# (<chunk>.<sha8>.js) and index.html is rewritten to point at it, rather than
# overwriting the original chunk in place. That is not cosmetic. Bundle chunks go
# out as `cache-control: public, max-age=31536000, immutable`, so overwriting one
# leaves browsers and every CDN edge serving the pre-patch bytes from a URL that,
# by contract, never revalidates - a purge of that URL was observed NOT to reach
# every Cloudflare PoP, and the badge stayed missing while the origin was provably
# correct. index.html is `no-cache` and never CDN-cached, so a new chunk name is
# picked up on the next page load, everywhere, with nothing to purge.
#
# Because the mounted index.html names a release-specific chunk, it must NOT stay
# mounted across an update: the new image would be served an index.html pointing at
# chunks it no longer has, breaking the app rather than just losing the badge.
# update.sh reverts before updating and re-applies afterwards. Do the same by hand
# if you update some other way.
#
# Exit status: 0 patched and live, 1 something did not apply.
set -eu

. "$(dirname "$(readlink -f "$0")")/lib.sh"
need_instance
PATCH_DIR="$OPS/patches"
OVERRIDE="$FLUXER_DIR/docker-compose.override.yml"
MARKER='# generated by ops/badge-patch.sh - do not edit by hand'
STATIC=/srv/app/static
ASSET_DIR="$STATIC/assets"

die() { printf 'badge-patch: %s\n' "$*" >&2; exit 1; }
compose() { (cd "$FLUXER_DIR" && docker compose "$@"); }

# Every override this script writes carries MARKER on its first line. Anything
# else in that path is someone else's file and is never touched.
ours() {
	[ -f "$OVERRIDE" ] || return 1
	head -n 1 "$OVERRIDE" | grep -qF "$MARKER"
}

app_proxy_image() {
	img=$(compose config --images 2>/dev/null | grep 'fluxer-app-proxy' | head -n 1) || img=''
	[ -n "$img" ] || die 'cannot resolve the app-proxy image from the compose config'
	printf '%s\n' "$img"
}

in_image() {
	docker run --rm --user "$(id -u):$(id -g)" --entrypoint sh -v "$1:/out" "$IMAGE" -c "$2"
}

# No mount: docker would create a root-owned directory at a bind source that does
# not exist yet, which this script then could not clean up.
in_image_ro() {
	docker run --rm --user "$(id -u):$(id -g)" --entrypoint sh "$IMAGE" -c "$1"
}

cmd_revert() {
	if [ -f "$OVERRIDE" ] && ! ours; then
		die "$OVERRIDE was not written by this script - remove the app-proxy mounts by hand"
	fi
	rm -f "$OVERRIDE"
	echo "Override removed. Recreating app-proxy on the stock bundle."
	compose up -d app-proxy
	rm -rf "$PATCH_DIR"
	echo "Done. The stock index.html points back at the stock chunk, so a reload is enough."
}

# node does the patch, the rewrite and both recompressions in one pass. Prefer the
# host's, fall back to the node that ships inside the api image so this works on a
# host with no node at all.
resolve_node() {
	NODE_BIN=$(command -v node 2>/dev/null || true)
	[ -n "$NODE_BIN" ] && return 0
	# nvm installs are not on PATH under cron or a plain sh.
	NODE_BIN=$(ls -d "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | sort -V | tail -n 1 || true)
}

run_node() {
	dir=$1 script=$2
	if [ -n "${NODE_BIN:-}" ]; then
		(cd "$dir" && "$NODE_BIN" "$script")
		return
	fi
	api_image=$(compose config --images 2>/dev/null | grep 'fluxer-api' | head -n 1) || api_image=''
	[ -n "$api_image" ] || die 'no node on this host and no api image to borrow one from'
	docker run --rm --user "$(id -u):$(id -g)" -v "$dir:/work" -w /work "$api_image" node "$script"
}

write_patch_program() {
	cat > "$1/patch.js" <<'NODE'
const fs = require('node:fs');
const zlib = require('node:zlib');
const crypto = require('node:crypto');
const chunk = fs.readFileSync('chunk.name', 'utf8').trim();

// Minified identifiers change between builds, so anchor on the shape of each
// condition rather than on this release's variable names. Each gate may appear at
// most once; every gate found is removed, and at least one must be.
const ID = '[A-Za-z_$][\\w$]*';
const PATH = `${ID}(?:\\.${ID})*`;
const GATES = [
	{
		// if (N || t.premiumType !== b.Gm.LIFETIME) {subscriber tooltip} else {Visionary tooltip}
		name: 'Visionary since tooltip',
		re: new RegExp(`\\((${ID})\\|\\|(${ID})\\.premiumType!==(${PATH})\\.LIFETIME\\)`, 'g'),
		to: (_m, _selfHosted, profile, constants) => `(${profile}.premiumType!==${constants}.LIFETIME)`,
	},
	{
		// !N && t.premiumType === b.Gm.LIFETIME && null != t.premiumLifetimeSequence
		name: 'Visionary ID badge',
		re: new RegExp(`!(${ID})&&(${ID})\\.premiumType===(${PATH})\\.LIFETIME&&null!=\\2\\.premiumLifetimeSequence`, 'g'),
		to: (_m, _selfHosted, profile, constants) =>
			`${profile}.premiumType===${constants}.LIFETIME&&null!=${profile}.premiumLifetimeSequence`,
	},
	{
		// Earlier releases: !E && (null == t ? void 0 : t.premiumType) && t.premiumType !== g.Gm.NONE
		name: 'Plutonium badge (earlier releases)',
		re: new RegExp(`!(${ID})&&\\(null==(${ID})\\?void 0:\\2\\.premiumType\\)&&\\2\\.premiumType!==(${PATH})\\.NONE`, 'g'),
		to: (_m, _selfHosted, profile, constants) =>
			`(null==${profile}?void 0:${profile}.premiumType)&&${profile}.premiumType!==${constants}.NONE`,
	},
];

const src = fs.readFileSync(chunk, 'utf8');
let patched = src;
const removed = [];
for (const gate of GATES) {
	const hits = patched.match(gate.re);
	if (!hits) continue;
	if (hits.length !== 1) {
		console.error(`patch: expected the ${gate.name} gate at most once, found it ${hits.length} times`);
		process.exit(3);
	}
	patched = patched.replace(gate.re, gate.to);
	gate.re.lastIndex = 0;
	if (gate.re.test(patched)) {
		console.error(`patch: the ${gate.name} replacement did not take`);
		process.exit(3);
	}
	removed.push(gate.name);
}
if (removed.length === 0) {
	console.error('patch: none of the self-hosted badge gates is in this bundle');
	process.exit(3);
}

// Content-derived name: identical content re-publishes to the same URL (so a
// no-op re-run changes nothing), and any change to the patch gets a fresh URL
// that no cache can have seen.
const body = Buffer.from(patched, 'utf8');
const sha8 = crypto.createHash('sha256').update(body).digest('hex').slice(0, 8);
const base = chunk.replace(/\.js$/, '');
const name = `${base}.${sha8}.js`;

// app-proxy serves whichever precompressed sibling the browser asks for, so the
// patched chunk needs its own .br and .gz or the originals would shadow it.
const publish = (file, buf, quality) => {
	fs.writeFileSync(file, buf);
	fs.writeFileSync(
		`${file}.br`,
		zlib.brotliCompressSync(buf, {
			params: {
				[zlib.constants.BROTLI_PARAM_QUALITY]: quality,
				[zlib.constants.BROTLI_PARAM_SIZE_HINT]: buf.length,
			},
		}),
	);
	fs.writeFileSync(`${file}.gz`, zlib.gzipSync(buf, {level: 9}));
};
publish(name, body, 11);

// Repoint the HTML. app-proxy templates index.html on every request (it injects
// __FLUXER_CONFIG__), so this file is a template, not a served artifact.
const html = fs.readFileSync('index.html', 'utf8');
if (!html.includes(`/assets/${chunk}`)) {
	console.error(`patch: index.html does not reference /assets/${chunk}`);
	process.exit(3);
}
publish('index.html', Buffer.from(html.replaceAll(`/assets/${chunk}`, `/assets/${name}`), 'utf8'), 5);

fs.writeFileSync('patched.name', `${name}\n`);
console.log(`  removed: ${removed.join(', ')}`);
console.log(`  published as ${name} (${body.length} bytes) and repointed index.html`);
NODE
}

cmd_apply() {
	if [ -f "$OVERRIDE" ] && ! ours; then
		die "$OVERRIDE already exists and was not written by this script - merge the mounts in by hand"
	fi
	IMAGE=$(app_proxy_image)

	# Read the bundle out of the image, not out of the running container, so a
	# re-run always starts from the pristine bytes of the current release.
	echo "Locating the bundle chunk that renders the badges, in $IMAGE."
	# The chunk holding a gate: the Visionary one (2026-10 on), else the old premium one.
	chunk=$(in_image_ro "grep -lE '\\.LIFETIME&&null!=[^&]+\\.premiumLifetimeSequence' $ASSET_DIR/*.js 2>/dev/null | head -n 2" \
		| tr -d '\r' | sed 's|.*/||')
	if [ -z "$chunk" ]; then
		chunk=$(in_image_ro "grep -lE '\\?void 0:[^?]+\\.premiumType\\)&&' $ASSET_DIR/*.js 2>/dev/null | head -n 2" \
			| tr -d '\r' | sed 's|.*/||')
	fi
	[ -n "$chunk" ] || die "no chunk in $ASSET_DIR has a self-hosted badge gate - did the bundle layout change?"
	[ "$(printf '%s\n' "$chunk" | wc -l)" -eq 1 ] \
		|| die "more than one chunk has a badge gate - patch them by hand: $chunk"
	echo "  $chunk"

	work="$PATCH_DIR.new"
	rm -rf "$work"
	mkdir -p "$work" "$PATCH_DIR"
	printf '%s\n' "$chunk" > "$work/chunk.name"
	in_image "$work" "cp $ASSET_DIR/$chunk $STATIC/index.html /out/"
	write_patch_program "$work"

	echo "Removing the gates and recompressing (brotli q11 on a few MB takes a moment)."
	resolve_node
	run_node "$work" patch.js || die 'the patch step failed - nothing was changed'
	name=$(cat "$work/patched.name")

	# Copy in over whatever is already mounted; never delete a mounted file, or
	# docker replaces the bind source with a root-owned directory on the next up.
	for f in "$name" "$name.br" "$name.gz" index.html index.html.br index.html.gz; do
		cat "$work/$f" > "$PATCH_DIR/$f"
	done
	printf '%s\n' "$chunk" > "$PATCH_DIR/chunk.name"
	printf '%s\n' "$name" > "$PATCH_DIR/patched.name"
	rm -rf "$work"

	cat > "$OVERRIDE" <<YAML
$MARKER
#
# Serves a patched copy of the app bundle chunk that renders profile badges, so
# the Visionary badge appears on this self-hosted instance, plus an index.html
# repointed at it. The stock chunk is left in place and simply stops being loaded.
# See ops/badge-patch.sh for why, and re-run it after every \`fluxer update\`:
# chunk names are release-specific.
services:
  app-proxy:
    volumes:
      # Absolute, not ./ops/patches/...: compose resolves relative bind sources
      # against the compose file's directory (\$FLUXER_DIR), which is only ./ops
      # when this checkout lives at \$FLUXER_DIR/ops. \$PATCH_DIR is always right.
      - $PATCH_DIR/$name:$ASSET_DIR/$name:ro
      - $PATCH_DIR/$name.br:$ASSET_DIR/$name.br:ro
      - $PATCH_DIR/$name.gz:$ASSET_DIR/$name.gz:ro
      - $PATCH_DIR/index.html:$STATIC/index.html:ro
      - $PATCH_DIR/index.html.br:$STATIC/index.html.br:ro
      - $PATCH_DIR/index.html.gz:$STATIC/index.html.gz:ro
YAML

	echo "Recreating app-proxy with the patched bundle."
	compose up -d app-proxy

	# Anything else in here is from an earlier release or an earlier patch. Safe to
	# drop now: the new override no longer names it, and the container is recreated.
	for f in "$PATCH_DIR"/*; do
		[ -e "$f" ] || continue
		case "$(basename "$f")" in
			"$name" | "$name.br" | "$name.gz") ;;
			index.html | index.html.br | index.html.gz | chunk.name | patched.name) ;;
			*) rm -f "$f" ;;
		esac
	done

	verify "$name"
}

verify() {
	name=$1
	path="/assets/$name"

	# app-proxy needs a moment to come back before it will serve the asset.
	i=0
	while [ "$i" -lt 30 ]; do
		code=$(compose exec -T edge wget -qS --spider "http://app-proxy:8080$path" 2>&1 \
			| sed -n 's/.*HTTP\/1\.[01] \([0-9]*\).*/\1/p' | head -n 1) || code=''
		[ "${code:-}" = "200" ] && break
		i=$((i + 1))
		sleep 1
	done
	[ "${code:-000}" = "200" ] || die "app-proxy still answers ${code:-no response} for $path"

	echo
	fail=0
	for enc in identity gzip br; do
		case "$enc" in
			identity) want=$(sha256sum "$PATCH_DIR/$name" | cut -d' ' -f1) ;;
			gzip) want=$(sha256sum "$PATCH_DIR/$name.gz" | cut -d' ' -f1) ;;
			br) want=$(sha256sum "$PATCH_DIR/$name.br" | cut -d' ' -f1) ;;
		esac
		# wget hands the body over untouched, so the precompressed siblings can be
		# compared byte for byte.
		got=$(compose exec -T edge wget -qO- --header="Accept-Encoding: $enc" \
			"http://app-proxy:8080$path" | sha256sum | cut -d' ' -f1)
		if [ "$got" = "$want" ]; then
			printf 'chunk      %-9s patched\n' "$enc"
		else
			printf 'chunk      %-9s WRONG BYTES\n' "$enc"
			fail=1
		fi
	done
	[ "$fail" -eq 0 ] || die 'app-proxy is not serving the patched chunk'

	# The HTML is what makes the patch reachable, and it is the one thing no cache
	# holds on to, so check it at the origin and through the public hostname.
	domain=$(sed -n 's/^FLUXER_DOMAIN=//p' "$FLUXER_DIR/.env" | head -n 1)
	[ -n "$domain" ] || die 'no FLUXER_DOMAIN in .env, cannot check the public URL'

	local_html=$(compose exec -T edge wget -qO- http://app-proxy:8080/ 2>/dev/null \
		| grep -c "/assets/$name" || true)
	[ "${local_html:-0}" -ge 1 ] && printf 'html       %-9s points at the patched chunk\n' 'app-proxy' \
		|| die 'the served index.html does not reference the patched chunk'

	pub_html=$(curl -s --max-time 30 "https://$domain/" | grep -c "/assets/$name" || true)
	[ "${pub_html:-0}" -ge 1 ] && printf 'html       %-9s points at the patched chunk\n' 'public' \
		|| die "https://$domain/ does not reference the patched chunk yet"

	pub_chunk=$(curl -s --max-time 120 -H 'Accept-Encoding: identity' "https://$domain$path" \
		| sha256sum | cut -d' ' -f1)
	[ "$pub_chunk" = "$(sha256sum "$PATCH_DIR/$name" | cut -d' ' -f1)" ] \
		&& printf 'chunk      %-9s patched\n' 'public' \
		|| die "https://$domain$path is not serving the patched bytes"

	echo
	echo "Visionary badge patch applied and live at $path. A normal reload picks it up."
}

case "${1:-apply}" in
	apply | '') cmd_apply ;;
	--revert | revert) cmd_revert ;;
	-h | --help | help) echo "usage: badge-patch.sh [apply|--revert]" ;;
	*) die "unknown argument: $1" ;;
esac
