#!/bin/sh
# firewall-fix.sh - make Docker survive firewalld starting underneath it.
#
# What actually breaks here (evidence from this host, 2026-09-13):
#
#   - Backends agree. iptables is iptables-nft (1.8.7, nf_tables) and firewalld
#     runs FirewallBackend=nftables, so this is not the legacy-vs-nft split.
#   - firewalld flushes every iptables table when it STARTS, not just on reload.
#     /etc/iptables/rules.v4 (netfilter-persistent) loads INPUT rules at boot, one
#     second before firewalld starts; the live INPUT chain is empty.
#   - On 2026-08-12 11:25:17 a mass service restart bounced dbus.service and
#     re-executed systemd. firewalld is Type=dbus, lost its bus, exited 1 and was
#     started again: a fresh start, which flushed the tables. docker was not
#     restarted (dockerd PID 894 ran from boot until 2026-09-13).
#   - Docker only hears about firewalld over D-Bus: a `Reloaded` signal, or
#     NameOwnerChanged when firewalld comes back (moby libnetwork/iptables/
#     firewalld.go). That connection is opened once and never re-established if
#     the bus itself restarts. So the old dockerd was deaf when firewalld came back
#     and never rebuilt its chains. Its failing command on 2026-09-13 was run as a
#     direct `iptables --wait ...` (exit status 1), not through firewalld's
#     passthrough, which is how a connected dockerd issues them (they show in
#     firewalld's log as `/usr/sbin/iptables -w10 ...`).
#   - A missing chain breaks nothing that is already running. It bites the next
#     time a container publishes a port, which here was 2026-09-13 14:42, a month
#     after the flush: `No chain/target/match by that name`.
#
# So `firewall-cmd --reload` is not the dangerous case: a connected dockerd
# handles it. The dangerous case is firewalld STARTING while docker is running,
# above all after a D-Bus restart has silently disconnected docker.
#
# The fix is a drop-in on firewalld.service:
#
#   ExecStartPost=-/usr/bin/systemctl --no-block try-restart docker.service
#
# Why this shape and not the alternatives:
#   - Every firewalld start runs it: `systemctl restart`, a crash-and-start, and
#     D-Bus activation alike. PartOf=/BindsTo= on docker.service only propagate
#     stop/restart JOBS, so the 2026-08-12 crash-then-start would not have
#     triggered them, and both make `systemctl stop firewalld` stop the stack.
#   - try-restart is a no-op when docker is not running. At boot docker is
#     After=firewalld.service, so it is still inactive when this runs, and the job
#     collapses to nothing: no double start.
#   - --no-block only enqueues the job. Without it systemctl would wait on a
#     docker restart that is itself ordered After= firewalld, which is still
#     activating inside ExecStartPost: a deadlock until the job times out.
#   - No loop: restarting docker never restarts firewalld. If firewalld is
#     stopped, a restarting docker may D-Bus-activate it, which triggers one more
#     docker restart, and then firewalld is running and it stops there.
#   - The leading `-` means a failure here never fails firewalld itself.
#   - A restart, not a "re-check chains" hook: docker < 28 does not fully restore
#     its rules even when it does get the signal (CVE-2025-54410), and Docker's own
#     advisory gives restarting the daemon as the workaround.
#
# The cost is one stack restart (every service is `unless-stopped`) per firewalld
# start outside boot. The journal shows two in three months. The watchdog stays:
# it is the backstop for anything this does not cover (a bare dbus restart that
# firewalld survives, an iptables flush by some other tool).
#
#   firewall-fix.sh              diagnose: evidence, and what --apply would do
#   firewall-fix.sh --apply      install the drop-in and daemon-reload (asks first)
#   firewall-fix.sh --revert     remove it and daemon-reload (asks first)
#   firewall-fix.sh --yes        with --apply/--revert: do not ask
#   firewall-fix.sh --installed  exit 0 if installed, 1 if not; prints nothing
#   firewall-fix.sh --test       how to verify it by hand (runs nothing)
#
# Nothing here restarts docker or firewalld. Paths are overridable for testing:
# SYSTEMD_DIR, SYSTEMCTL, SUDO.
set -eu

FLUXER_DIR=${FLUXER_DIR:-/home/ubuntu/Documents/fluxer}
SYSTEMD_DIR=${SYSTEMD_DIR:-/etc/systemd/system}
SYSTEMCTL=${SYSTEMCTL:-systemctl}
SUDO=${SUDO-sudo}
[ "$(id -u)" -eq 0 ] && SUDO=''
DROPIN_DIR="$SYSTEMD_DIR/firewalld.service.d"
DROPIN="$DROPIN_DIR/50-fluxer-restart-docker.conf"
MARKER='# generated by ops/firewall-fix.sh - do not edit by hand'

die() { printf 'firewall-fix: %s\n' "$*" >&2; exit 1; }
as_root() { if [ -n "$SUDO" ]; then "$SUDO" "$@"; else "$@"; fi; }
ours() { [ -f "$DROPIN" ] && head -n 1 "$DROPIN" | grep -qF "$MARKER"; }

dropin_body() {
	cat <<EOF
$MARKER
#
# firewalld flushes every iptables table when it starts, including Docker's
# chains, and Docker does not reliably rebuild them (it hears about firewalld only
# over a D-Bus connection that does not survive a dbus restart). So every time
# firewalld starts while docker is running, restart docker afterwards.
# try-restart: no-op at boot, when docker has not started yet.
# --no-block: docker is After=firewalld, so waiting here would deadlock.
# See ops/firewall-fix.sh.
[Service]
ExecStartPost=-$(command -v systemctl || echo /usr/bin/systemctl) --no-block try-restart docker.service
EOF
}

confirm() {
	[ "$ASSUME_YES" -eq 1 ] && return 0
	printf '%s [y/N] ' "$1"
	read -r reply
	case "$reply" in
		y | Y | yes | YES) ;;
		*) echo "Aborted. Nothing changed."; exit 0 ;;
	esac
}

unit_prop() { systemctl show "$1" -p "$2" --value 2>/dev/null || true; }

cmd_diagnose() {
	echo "Docker vs firewalld on this host"
	echo

	printf 'docker       %s\n' "$(docker version --format '{{.Server.Version}}' 2>/dev/null || echo unknown)"
	printf 'firewalld    %s, %s\n' "$(dpkg-query -W -f '${Version}' firewalld 2>/dev/null || echo unknown)" "$(systemctl is-active firewalld 2>/dev/null || true)"
	printf 'iptables     %s\n' "$(iptables --version 2>/dev/null || echo 'not found')"
	backend=$(sudo -n sed -n 's/^FirewallBackend=//p' /etc/firewalld/firewalld.conf 2>/dev/null || true)
	printf 'fw backend   %s\n' "${backend:-unreadable (needs sudo)}"
	case "$(iptables --version 2>/dev/null)|$backend" in
		*nf_tables*'|nftables' | *nf_tables*'|') echo "ok    iptables and firewalld both drive nftables: no legacy/nft split" ;;
		*legacy*'|nftables') echo "warn  iptables is legacy but firewalld is nftables: Docker's rules and firewalld's live in different stacks" ;;
		*) ;;
	esac

	if sudo -n iptables -t nat -L -n 2>/dev/null | grep -q '^Chain DOCKER'; then
		echo "ok    DOCKER nat chain present"
	elif sudo -n true 2>/dev/null; then
		echo "FAIL  DOCKER nat chain MISSING - run: sudo systemctl restart docker"
	else
		echo "skip  DOCKER nat chain (needs passwordless sudo)"
	fi

	# Is docker still connected to the system bus? If not, it will not hear the
	# next firewalld reload or restart.
	dpid=$(unit_prop docker.service MainPID)
	if [ -n "$dpid" ] && [ "$dpid" != 0 ] && command -v busctl > /dev/null 2>&1 \
		&& systemctl is-active --quiet firewalld; then
		if busctl --system list --no-pager 2>/dev/null | awk -v p="$dpid" '$2 == p {f=1} END {exit !f}'; then
			echo "ok    dockerd (pid $dpid) holds a live D-Bus connection: it will hear firewalld"
		else
			echo "FAIL  dockerd (pid $dpid) has NO D-Bus connection: it cannot hear firewalld"
			echo "      A firewalld reload or restart will now wipe its chains for good."
			echo "      Restart docker at a quiet moment: sudo systemctl restart docker"
		fi
	fi

	d_t=$(unit_prop docker.service ActiveEnterTimestampMonotonic)
	for u in firewalld dbus; do
		t=$(unit_prop "$u.service" ActiveEnterTimestampMonotonic)
		case "$t$d_t" in '' | *[!0-9]*) continue ;; esac
		if [ "$t" -gt "$d_t" ]; then
			echo "warn  $u started after docker ($(unit_prop "$u.service" ActiveEnterTimestamp)) - docker may have missed it"
		else
			echo "ok    $u has not (re)started since docker did"
		fi
	done

	# firewalld starts more than 5 minutes after boot are the ones that hurt.
	late=$(journalctl -u firewalld -o json --no-pager 2>/dev/null | python3 -c '
import datetime, json, sys
for line in sys.stdin:
    try:
        e = json.loads(line)
    except ValueError:
        continue
    if str(e.get("MESSAGE", "")).startswith("Started firewalld") \
            and int(e.get("__MONOTONIC_TIMESTAMP", 0)) > 300 * 10**6:
        t = int(e["__REALTIME_TIMESTAMP"]) // 10**6
        print(datetime.datetime.fromtimestamp(t, datetime.timezone.utc).strftime("%Y-%m-%dT%H:%MZ"), end=" ")
' 2>/dev/null || true)
	if [ -n "$late" ]; then
		echo "warn  firewalld started outside boot (journal): $late"
	else
		echo "ok    firewalld never started outside boot, as far back as the journal goes"
	fi

	if systemctl is-enabled netfilter-persistent > /dev/null 2>&1; then
		echo "note  netfilter-persistent is enabled too; firewalld flushes what it loads at boot"
	fi

	case "$(docker version --format '{{.Server.Version}}' 2>/dev/null)" in
		[0-9].* | 1[0-9].* | 2[0-7].*)
			echo "note  docker < 28 does not fully restore its rules even on a clean firewall-cmd --reload"
			echo "      (CVE-2025-54410: bridge isolation rules). Upgrading docker fixes that part." ;;
	esac

	echo
	if ours; then
		echo "ok    fix installed: $DROPIN"
		if [ "$SYSTEMD_DIR" = /etc/systemd/system ]; then
			case "$(unit_prop firewalld.service DropInPaths)" in
				*"$DROPIN"*) echo "ok    systemd has loaded it" ;;
				*) echo "warn  systemd has not loaded it yet - run: sudo systemctl daemon-reload" ;;
			esac
		fi
		echo
		echo "Undo with: $0 --revert"
	else
		[ -e "$DROPIN" ] && echo "warn  $DROPIN exists but was not written by this script"
		echo "warn  fix NOT installed"
		echo
		echo "--apply would write $DROPIN:"
		echo
		dropin_body | sed 's/^/    /'
		echo
		echo "then run 'systemctl daemon-reload'. It restarts nothing now: it takes effect"
		echo "the next time firewalld starts. That start will restart docker (about a"
		echo "minute of downtime while the stack comes back)."
	fi
	echo
	echo "To verify it by hand: $0 --test"
}

cmd_test() {
	cat <<EOF
Verifying by hand. Step 2 restarts the whole stack, so pick a quiet moment.

1. Reload (docker should cope on its own, no restart expected):
     sudo firewall-cmd --reload
     sleep 5; sudo iptables -t nat -L -n | grep '^Chain DOCKER'   # must print
     $FLUXER_DIR/ops/check.sh

2. firewalld restart (the case this fix is for):
     systemctl show docker -p ActiveEnterTimestamp                # note it
     sudo systemctl restart firewalld
     sleep 60
     systemctl show docker -p ActiveEnterTimestamp                # must be newer
     sudo iptables -t nat -L -n | grep '^Chain DOCKER'            # must print
     $FLUXER_DIR/ops/check.sh

   Without the fix, step 2 leaves docker running on the old timestamp and, if its
   D-Bus connection is gone, no DOCKER chain.

3. Boot: after the next reboot, docker should have started exactly once:
     journalctl -b -u docker | grep -c 'Started Docker'           # 1
EOF
}

cmd_apply() {
	if [ -e "$DROPIN" ] && ! ours; then
		die "$DROPIN exists and was not written by this script - merge by hand"
	fi
	[ -d "$SYSTEMD_DIR" ] || die "no $SYSTEMD_DIR"
	"$SYSTEMCTL" cat firewalld.service > /dev/null 2>&1 || die "firewalld.service is not installed"

	tmp=$(mktemp)
	trap 'rm -f "$tmp"' EXIT
	dropin_body > "$tmp"
	if ours && cmp -s "$tmp" "$DROPIN"; then
		echo "Already installed and current: $DROPIN"
		exit 0
	fi

	echo "Will write $DROPIN:"
	echo
	sed 's/^/    /' "$tmp"
	echo
	echo "and run systemctl daemon-reload. Nothing is restarted now."
	confirm 'Install it?'

	as_root mkdir -p "$DROPIN_DIR"
	as_root install -m 644 "$tmp" "$DROPIN"
	as_root "$SYSTEMCTL" daemon-reload
	echo "Installed $DROPIN and reloaded systemd."

	if [ "$SYSTEMD_DIR" = /etc/systemd/system ]; then
		case "$(unit_prop firewalld.service DropInPaths)" in
			*"$DROPIN"*) echo "systemd has loaded it." ;;
			*) die "systemd does not list $DROPIN for firewalld.service - check: systemctl cat firewalld" ;;
		esac
	fi
	echo "It takes effect the next time firewalld starts. Verify with: $0 --test"
}

cmd_revert() {
	if [ ! -e "$DROPIN" ]; then
		echo "Not installed. Nothing to do."
		exit 0
	fi
	ours || die "$DROPIN was not written by this script - remove it by hand"
	echo "Will remove $DROPIN and run systemctl daemon-reload. Nothing is restarted."
	confirm 'Remove it?'
	as_root rm -f "$DROPIN"
	as_root rmdir "$DROPIN_DIR" 2> /dev/null || true
	as_root "$SYSTEMCTL" daemon-reload
	echo "Removed. Docker is back to depending on its D-Bus connection and the watchdog."
}

ASSUME_YES=0
action=diagnose
for a in "$@"; do
	case "$a" in
		--apply) action=apply ;;
		--revert) action=revert ;;
		--installed) action=installed ;;
		--test) action='test' ;;
		--yes | -y) ASSUME_YES=1 ;;
		-h | --help) sed -n '/^#   firewall-fix.sh /s/^# *//p' "$0"; exit 0 ;;
		*) echo "usage: firewall-fix.sh [--apply|--revert|--installed|--test] [--yes]" >&2; exit 2 ;;
	esac
done

case "$action" in
	diagnose) cmd_diagnose ;;
	apply) cmd_apply ;;
	revert) cmd_revert ;;
	installed) ours ;;
	test) cmd_test ;;
esac
