#!/bin/sh
# overlay.sh - the one writer of docker-compose.override.yml and of the index.html the
# web app is served with.
#
#   overlay.sh apply     rebuild both from the features that are on, recreate what changed
#   overlay.sh suspend   drop the override (stock app and edge), keep every feature's state
#   overlay.sh status    which features are on
#
# Two features change what the browser gets, and both need index.html:
#   badge   badge-patch.sh: patched chunks in ops/patches/ and patches/index.html
#           repointed at them. On while ops/patches/patched.names is non-empty.
#   panel   panel.sh: a <script> for the STAFF Ops panel in index.html, plus a Caddyfile
#           with the /ops-api/ route, the bridge's socket directory and the script
#           itself mounted into edge. On while ops/panel/enabled exists.
# Each feature keeps its own files; this composes them, so turning one off never takes
# the other with it. index.html is built in one pass: stock (or the badge's repointed
# copy), then the panel's <script>.
#
# A badge patch built for another release (after an update) is left out with a warning
# instead of mounted: its index.html names chunks the new image no longer has, which
# would break the app outright rather than just lose the badge.
set -eu

. "$(dirname "$(readlink -f "${OPS_SELF:-$0}")")/lib.sh"
. "$OPS/lib-node.sh"

OVERRIDE="$FLUXER_DIR/docker-compose.override.yml"
MARKER='# generated by ops/overlay.sh - do not edit by hand'
# Written by badge-patch.sh before overlay.sh existed; still ours to replace.
LEGACY_MARKER='# generated by ops/badge-patch.sh - do not edit by hand'
PATCH_DIR="$OPS/patches"
PANEL_DIR="$OPS/panel"
OUT_DIR="$OPS/overlay"
STATIC=/srv/app/static
ASSET_DIR="$STATIC/assets"
PANEL_TAG='<script nonce="{{CSP_NONCE_PLACEHOLDER}}" src="/ops-panel.js"></script>'

die() { printf 'overlay: %s\n' "$*" >&2; exit 1; }
compose() { (cd "$FLUXER_DIR" && docker compose "$@"); }

# Anything else at that path is someone else's file and is never touched.
ours() {
	[ -f "$OVERRIDE" ] || return 1
	first=$(head -n 1 "$OVERRIDE")
	[ "$first" = "$MARKER" ] || [ "$first" = "$LEGACY_MARKER" ]
}
badge_on() { [ -s "$PATCH_DIR/patched.names" ] && [ -s "$PATCH_DIR/chunk.name" ] && [ -f "$PATCH_DIR/index.html" ]; }
# On means enabled AND everything it mounts is there: a missing bind source makes docker
# create a root-owned directory in its place, and edge then fails to start.
panel_enabled() { [ -f "$PANEL_DIR/enabled" ]; }
panel_complete() { [ -f "$PANEL_DIR/Caddyfile" ] && [ -d "$PANEL_DIR/www" ] && [ -d "$PANEL_DIR/run" ]; }
# The panel's Caddyfile is a copy of upstream's plus a marked block. If upstream's changed
# since (an update), mounting the copy would pin edge to the old file.
panel_fresh() { sed '/# >>> fluxer-ops panel/,/# <<< fluxer-ops panel/d' "$PANEL_DIR/Caddyfile" | cmp -s - "$FLUXER_DIR/Caddyfile"; }
panel_on() { panel_enabled && panel_complete && panel_fresh; }

app_proxy_image() {
	img=$(compose config --images 2> /dev/null | grep 'fluxer-app-proxy' | head -n 1) || img=''
	[ -n "$img" ] || die 'cannot resolve the app-proxy image from the compose config'
	printf '%s\n' "$img"
}

# Was the badge patch built from the release app-proxy runs now? Its stock chunk is
# still in the image only if so, and so is every other release-specific file its
# index.html names (entry, loaders, runtime) that the patch did not replace. One probe.
badge_current() {
	needed=$(cat "$PATCH_DIR/chunk.name")
	patched=" $(tr '\n' ' ' < "$PATCH_DIR/patched.names")"
	for n in $(grep -o '/assets/[A-Za-z0-9._-]*' "$PATCH_DIR/index.html" | sed 's|^/assets/||' | sort -u); do
		case "$patched" in
			*" $n "*) ;;
			*) needed="$needed $n" ;;
		esac
	done
	# shellcheck disable=SC2016 # the container's shell expands $f and $@
	docker run --rm --pull never --entrypoint sh "$(app_proxy_image)" \
		-c 'd=$1; shift; for f; do test -f "$d/$f" || exit 1; done' sh "$ASSET_DIR" $needed > /dev/null 2>&1
}

# The badge's files to mount, space-separated, or nothing when it is off or stale.
badge_names() {
	badge_on || return 0
	if badge_current; then
		tr '\n' ' ' < "$PATCH_DIR/patched.names"
	else
		echo "overlay: the badge patch was built for another release; leaving it out until 'fluxer badge-patch' rebuilds it" >&2
	fi
}

# The html with the panel's <script> right before the first external script. It must
# run before the bundle: the app deletes window.localStorage at start-up, and the panel
# wraps XMLHttpRequest before the app's first api call. A classic script there runs
# before every module script, which are deferred. Exit 3: nowhere to put it.
insert_panel_tag() {
	awk -v tag="$PANEL_TAG" '
		!done && /<script[^>]* src=/ { sub(/<script[^>]* src=/, tag "&"); done = 1 }
		{ print }
		END { if (!done) exit 3 }' "$1"
}

render_override() { # <badge names> <panel 0|1>
	printf '%s\n' "$MARKER"
	cat <<'YAML'
#
# Composed by ops/overlay.sh from the features that are on: the Visionary badge patch
# (badge-patch.sh) and the STAFF Ops panel (panel.sh). Regenerated by those scripts and
# by update.sh; never edit by hand. Sources are absolute: compose resolves relative
# bind sources against $FLUXER_DIR, which is ops/'s parent only in the usual layout.
services:
  app-proxy:
    volumes:
YAML
	for n in $1; do
		for f in "$n" "$n.br" "$n.gz"; do
			printf '      - %s/%s:%s/%s:ro\n' "$PATCH_DIR" "$f" "$ASSET_DIR" "$f"
		done
	done
	for f in index.html index.html.br index.html.gz; do
		printf '      - %s/%s:%s/%s:ro\n' "$OUT_DIR" "$f" "$STATIC" "$f"
	done
	[ "$2" = 1 ] || return 0
	cat <<YAML
  edge:
    volumes:
      # Same container path as upstream's ./Caddyfile mount, so this one replaces it.
      - $PANEL_DIR/Caddyfile:/etc/caddy/Caddyfile:ro
      - $PANEL_DIR/www:/srv/ops-panel:ro
      # The directory, not the socket: the bridge recreates the socket on restart.
      - $PANEL_DIR/run:/run/fluxer-ops
YAML
}

write_compress_program() {
	cat > "$1/compress.js" <<'NODE'
// app-proxy serves whichever precompressed sibling the browser asks for, so the
// composed index.html needs its own .br and .gz or the stock ones would shadow it.
const fs = require('node:fs');
const zlib = require('node:zlib');
const html = fs.readFileSync('index.html');
fs.writeFileSync('index.html.br', zlib.brotliCompressSync(html, {
	params: {[zlib.constants.BROTLI_PARAM_QUALITY]: 5},
}));
fs.writeFileSync('index.html.gz', zlib.gzipSync(html, {level: 9}));
NODE
}

cmd_apply() {
	need_instance
	if [ -f "$OVERRIDE" ] && ! ours; then
		die "$OVERRIDE was not written by fluxer-ops - merge its mounts by hand"
	fi
	names=$(badge_names)
	panel=0
	if panel_on; then
		panel=1
	elif panel_enabled; then
		if panel_complete; then
			echo "overlay: the Ops panel's Caddyfile was built from an older upstream Caddyfile; leaving the panel out (run: fluxer panel refresh)" >&2
		else
			echo "overlay: the Ops panel is enabled but ops/panel/ is incomplete (Caddyfile, www/ or run/ missing); leaving it out until it is restored (run: fluxer panel refresh)" >&2
		fi
	fi

	if [ -z "$names" ] && [ "$panel" = 0 ]; then
		if ours; then
			rm -f "$OVERRIDE"
			echo "Nothing to serve on top of the stock app: override removed."
			compose up -d --no-deps app-proxy edge
		fi
		return 0
	fi

	work="$OUT_DIR.new"
	rm -rf "$work"
	mkdir -p "$work" "$OUT_DIR"
	if [ -n "$names" ]; then
		cp "$PATCH_DIR/index.html" "$work/base.html"
	else
		# Read from the image, never the running container: always the pristine bytes.
		docker run --rm --user "$(id -u):$(id -g)" --entrypoint sh -v "$work:/out" "$(app_proxy_image)" \
			-c "cp $STATIC/index.html /out/base.html"
	fi
	if [ "$panel" = 1 ]; then
		insert_panel_tag "$work/base.html" > "$work/index.html" \
			|| die "index.html has no external <script> to put the panel before - did the bundle layout change?"
	else
		cp "$work/base.html" "$work/index.html"
	fi
	write_compress_program "$work"
	resolve_node
	run_node "$work" compress.js || die 'compressing index.html failed - nothing was changed'

	# Copy in over what is mounted; never delete a mounted file, or docker replaces the
	# bind source with a root-owned directory on the next up.
	for f in index.html index.html.br index.html.gz; do
		cat "$work/$f" > "$OUT_DIR/$f"
	done
	rm -rf "$work"
	render_override "$names" "$panel" > "$OVERRIDE.new"
	mv "$OVERRIDE.new" "$OVERRIDE"
	compose up -d --no-deps app-proxy edge
	printf 'Client overlay: badge %s, Ops panel %s.\n' \
		"$([ -n "$names" ] && echo on || echo off)" "$([ "$panel" = 1 ] && echo on || echo off)"
}

cmd_suspend() {
	need_instance
	if ! ours; then
		echo "No fluxer-ops override in place."
		return 0
	fi
	rm -f "$OVERRIDE"
	compose up -d --no-deps app-proxy edge
	echo "Override removed: app and edge are stock until 'overlay.sh apply' (features keep their state)."
}

cmd_status() {
	need_instance
	printf 'badge   %s\n' "$(badge_on && echo on || echo off)"
	printf 'panel   %s\n' "$(panel_on && echo on || echo off)"
	if ours; then echo "override  ours ($OVERRIDE)"
	elif [ -f "$OVERRIDE" ]; then echo "override  someone else's ($OVERRIDE)"
	else echo "override  none (stock app)"; fi
}

[ "${OVERLAY_SOURCE_ONLY:-0}" = 1 ] && return 0

case "${1:-status}" in
	apply) cmd_apply ;;
	suspend) cmd_suspend ;;
	status) cmd_status ;;
	-h | --help | help) echo "usage: overlay.sh [apply|suspend|status]" ;;
	*) die "unknown command: $1 (apply, suspend, status)" ;;
esac
