#!/bin/sh
# panel.sh - the STAFF "Ops" panel: run the account and health commands from the web
# app's STAFF menu instead of a shell. Design: docs/superpowers/specs/2026-10-08-staff-ops-panel-design.md
#
#   panel.sh on        install and start the bridge, add the route and the script
#   panel.sh off       the kill switch: stop the bridge, drop the route and the script
#   panel.sh status    is it on, is the bridge answering, is the route live
#   panel.sh refresh   rebuild from upstream's current Caddyfile and re-apply (update.sh runs it)
#
# Three pieces:
#   ops_bridge.py   systemd unit fluxer-ops-bridge, as this user and never root
#                   (NoNewPrivileges: nothing it starts can sudo). It checks the caller's
#                   session and STAFF flag, then runs one allowlisted script.
#   ops-panel.js    served by edge at /ops-panel.js; overlay.sh puts it in index.html.
#   Caddyfile       a copy of upstream's with a marked /ops-api/* block before the
#                   catch-all. Upstream's own file is never edited.
# The socket lives in ops/panel/run, a directory on disk rather than /run: after a
# reboot docker starts edge before the bridge, and a missing bind source would be
# created root-owned, where the bridge could not create its socket.
#
# Web app only: the desktop and mobile apps never load this server's index.html.
set -eu

. "$(dirname "$(readlink -f "${OPS_SELF:-$0}")")/lib.sh"
PANEL_DIR="$OPS/panel"
SOCKET="$PANEL_DIR/run/bridge.sock"
UNIT=fluxer-ops-bridge
UNIT_FILE="/etc/systemd/system/$UNIT.service"
PANEL_TAG='<script src="/ops-panel.js"></script>'

die() { printf 'panel: %s\n' "$*" >&2; exit 1; }
compose() { (cd "$FLUXER_DIR" && docker compose "$@"); }
domain() { sed -n 's/^FLUXER_DOMAIN=//p' "$FLUXER_DIR/.env" 2> /dev/null | head -n 1; }

# GET through edge on this host. Cloudflare in front would cache, and a failure there
# says nothing about this server. Prints the status code; the body goes to $2.
origin_get() {
	d=$(domain)
	curl -s --max-time 15 -o "${2:-/dev/null}" -w '%{http_code}' --resolve "$d:443:127.0.0.1" "https://$d$1" || true
}
bridge_health() { curl -s --max-time 3 --unix-socket "$SOCKET" http://bridge/health 2> /dev/null | grep -q '"ok": *true'; }

render_caddyfile() { # <upstream Caddyfile>
	awk '
		/^\thandle [{]$/ {
			n++
			if (n == 1) {
				print "\t# >>> fluxer-ops panel (ops/panel.sh): the bridge API and the panel script"
				print "\thandle_path /ops-api/* {"
				print "\t\treverse_proxy unix//run/fluxer-ops/bridge.sock"
				print "\t}"
				print "\thandle /ops-panel.js {"
				print "\t\troot * /srv/ops-panel"
				print "\t\theader Cache-Control \"no-cache\""
				print "\t\tfile_server"
				print "\t}"
				print "\t# <<< fluxer-ops panel"
			}
		}
		{ print }
		END { if (n != 1) exit 3 }' "$1"
}

render_unit() { # <user> <group> <python3>
	cat <<EOF
# generated by ops/panel.sh - do not edit by hand
[Unit]
Description=fluxer-ops bridge for the in-app STAFF Ops panel (ops/panel.sh)
After=docker.service
Wants=docker.service

[Service]
User=$1
Group=$2
SupplementaryGroups=docker
Environment=FLUXER_DIR=$FLUXER_DIR
ExecStart=$3 -I $OPS/ops_bridge.py --socket $SOCKET
Restart=always
RestartSec=2
UMask=0007
NoNewPrivileges=yes
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
EOF
}

# until <seconds> <command...>: retry once a second.
until_ok() {
	n=$1
	shift
	i=0
	until "$@"; do
		i=$((i + 1))
		[ "$i" -lt "$n" ] || return 1
		sleep 1
	done
}
route_live() { [ "$(origin_get /ops-api/health)" = 200 ]; }
script_live() { [ "$(origin_get /ops-panel.js)" = 200 ]; }
html_loads_panel() {
	f=$(mktemp)
	origin_get / "$f" > /dev/null
	rc=0
	grep -qF "$PANEL_TAG" "$f" || rc=$?
	rm -f "$f"
	return "$rc"
}

reload_edge() {
	compose exec -T edge caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile > /dev/null 2>&1
}

# The panel is switched on by now: say so, and how to take it off.
die_still_on() {
	die "$* The panel is still ON; 'fluxer panel off' removes it."
}

cmd_on() {
	need_instance
	[ -n "$(domain)" ] || die "no FLUXER_DOMAIN in $FLUXER_DIR/.env"
	[ -f "$OPS/ops-panel.js" ] || die "$OPS/ops-panel.js is missing"
	command -v python3 > /dev/null 2>&1 || die 'the bridge needs python3'
	command -v curl > /dev/null 2>&1 || die 'checking the bridge needs curl'
	id -nG | tr ' ' '\n' | grep -qx docker \
		|| die "$(id -un) is not in the docker group, so the bridge could not run the scripts"

	mkdir -p "$PANEL_DIR/www" "$PANEL_DIR/run"
	if ! render_caddyfile "$FLUXER_DIR/Caddyfile" > "$PANEL_DIR/Caddyfile.new"; then
		rm -f "$PANEL_DIR/Caddyfile.new"
		die "$FLUXER_DIR/Caddyfile has no single catch-all 'handle {' to put the route before"
	fi
	# Checked with edge's own Caddy before anything goes live: a bad file must not be mounted.
	if ! compose exec -T edge caddy adapt --adapter caddyfile --config /dev/stdin \
		< "$PANEL_DIR/Caddyfile.new" > /dev/null; then
		rm -f "$PANEL_DIR/Caddyfile.new"
		die "edge (is it running?) rejected the panel's Caddyfile; nothing was changed"
	fi

	render_unit "$(id -un)" "$(id -gn)" "$(command -v python3)" > "$PANEL_DIR/unit.new"
	if ! cmp -s "$PANEL_DIR/unit.new" "$UNIT_FILE"; then
		echo "Installing $UNIT_FILE (sudo)."
		sudo install -m 0644 "$PANEL_DIR/unit.new" "$UNIT_FILE"
		sudo systemctl daemon-reload
	fi
	rm -f "$PANEL_DIR/unit.new"
	sudo systemctl enable "$UNIT" > /dev/null 2>&1
	sudo systemctl restart "$UNIT"
	if ! until_ok 15 bridge_health; then
		rm -f "$PANEL_DIR/Caddyfile.new"
		sudo systemctl disable --now "$UNIT" > /dev/null 2>&1 || true
		die "the bridge does not answer on $SOCKET; it was stopped and disabled so it does not crash-loop - see: journalctl -u $UNIT -n 50"
	fi
	echo "Bridge answering on $SOCKET."

	# Copied over, never replaced: edge has the Caddyfile mounted as a file, and a
	# replaced file would leave it reading the old inode.
	had_prev=0
	if [ -f "$PANEL_DIR/Caddyfile" ]; then
		cp "$PANEL_DIR/Caddyfile" "$PANEL_DIR/Caddyfile.prev"
		had_prev=1
	fi
	cat "$PANEL_DIR/Caddyfile.new" > "$PANEL_DIR/Caddyfile"
	rm -f "$PANEL_DIR/Caddyfile.new"
	cat "$OPS/ops-panel.js" > "$PANEL_DIR/www/ops-panel.js"

	: > "$PANEL_DIR/enabled"
	"$OPS/overlay.sh" apply
	# A Caddyfile that changed under an edge that was not recreated needs a reload. Edge may
	# have just been recreated, its admin API not listening yet, hence the retries.
	if ! until_ok 10 reload_edge; then
		compose exec -T edge caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile > /dev/null || true
		if [ "$had_prev" -eq 1 ]; then
			cat "$PANEL_DIR/Caddyfile.prev" > "$PANEL_DIR/Caddyfile"
			rm -f "$PANEL_DIR/Caddyfile.prev"
			die "edge refused the panel's Caddyfile; the previous copy is back in ops/panel/Caddyfile. The panel is still ON; 'fluxer panel off' removes it."
		fi
		rm -f "$PANEL_DIR/enabled" "$PANEL_DIR/Caddyfile.prev"
		"$OPS/overlay.sh" apply || true
		die "edge refused the panel's Caddyfile; the panel was switched back off and edge is on upstream's Caddyfile again"
	fi
	rm -f "$PANEL_DIR/Caddyfile.prev"

	until_ok 30 route_live || die_still_on "edge does not answer /ops-api/health: the route is not live."
	until_ok 30 script_live || die_still_on "edge does not serve /ops-panel.js."
	until_ok 30 html_loads_panel || die_still_on "the served index.html does not load /ops-panel.js."
	echo
	echo "Ops panel on. Reload the web app, then STAFF menu -> Ops…"
	echo "(Web app only: the desktop and mobile apps never load this server's index.html.)"
}

# Bridge first: the part that can run commands goes before anything else. Whatever
# fails, the switch and the overlay still come off.
cmd_off() {
	need_instance
	rc=0
	if ! sudo systemctl disable --now "$UNIT" > /dev/null; then
		echo "panel: could not stop and disable $UNIT - do it by hand: sudo systemctl disable --now $UNIT" >&2
		rc=1
	fi
	rm -f "$PANEL_DIR/enabled"
	"$OPS/overlay.sh" apply || rc=1
	if [ "$rc" -eq 0 ]; then
		echo "Ops panel off: the script, the route and the bridge are gone. Open clients lose it on their next reload."
	else
		echo "panel: the panel is switched off but something above failed; check before relying on it." >&2
	fi
	return "$rc"
}

cmd_refresh() {
	if [ ! -f "$PANEL_DIR/enabled" ]; then
		echo "Ops panel is off; nothing to refresh."
		return 0
	fi
	cmd_on
}

cmd_status() {
	need_instance
	if [ -f "$PANEL_DIR/enabled" ]; then echo "panel   on"; else echo "panel   off"; fi
	state=$(systemctl is-active "$UNIT" 2> /dev/null || true)
	echo "bridge  ${state:-unknown} ($UNIT)"
	if bridge_health; then echo "socket  answering ($SOCKET)"; else echo "socket  not answering ($SOCKET)"; fi
	if [ -f "$PANEL_DIR/enabled" ]; then
		if route_live; then echo "route   live through edge"; else echo "route   NOT live through edge"; fi
	fi
}

[ "${PANEL_SOURCE_ONLY:-0}" = 1 ] && return 0

case "${1:-status}" in
	on) cmd_on ;;
	off) cmd_off ;;
	status) cmd_status ;;
	refresh) cmd_refresh ;;
	-h | --help | help) echo "usage: panel.sh on | off | status | refresh" ;;
	*) die "unknown command: $1 (on, off, status, refresh)" ;;
esac
