#!/bin/sh
# overlay_test.sh - overlay.sh composes the badge patch and the Ops panel into one
# override and one index.html. Stubs only: docker never reaches the real instance.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
SRC=$(dirname "$HERE")
. "$HERE/assert.sh"
tmp=$(readlink -f "$(mktemp -d)")
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/inst/ops/patches" "$tmp/stub"
cp "$SRC"/*.sh "$tmp/inst/ops/"
: > "$tmp/inst/docker-compose.yml"
printf 'FLUXER_DOMAIN=chat.example.test\n' > "$tmp/inst/.env"

# docker stub: logs every call; `compose config --images` names an image, `run` exits
# with $DOCKER_RUN_RC (the "is this chunk still in the image" probe).
cat > "$tmp/stub/docker" <<'EOF'
#!/bin/sh
printf '%s\n' "$*" >> "$DOCKER_LOG"
case "$1 $2" in
	"compose config") echo ghcr.io/fluxerapp/fluxer-app-proxy-self-hosted:v1; exit 0 ;;
	"compose up") exit 0 ;;
esac
if [ "$1" = run ]; then
	for a in "$@"; do
		case "$a" in
			# The copy of the stock index.html out of the image.
			*:/out) cat "$STOCK_HTML" > "${a%:/out}/base.html"; exit 0 ;;
		esac
		# Files named in $DOCKER_MISSING are "not in the image".
		for m in ${DOCKER_MISSING:-}; do
			[ "$a" = "$m" ] && exit 1
		done
	done
	exit "${DOCKER_RUN_RC:-0}"
fi
exit 0
EOF
chmod +x "$tmp/stub/docker"
# node stub: compress.js is replaced by copies, enough to check what gets composed.
cat > "$tmp/stub/node" <<'EOF'
#!/bin/sh
cp index.html index.html.br
cp index.html index.html.gz
EOF
chmod +x "$tmp/stub/node"
export STOCK_HTML="$tmp/stock.html"
printf '<html><script nonce="n">stock</script><script src="/assets/stock-entry.js"></script></html>\n' > "$STOCK_HTML"
export DOCKER_LOG="$tmp/docker.log"
: > "$DOCKER_LOG"
PATH="$tmp/stub:$PATH"

load() {
	# shellcheck disable=SC2034 # read by the sourced overlay.sh and lib.sh
	FLUXER_DIR="$tmp/inst" OPS_SELF="$tmp/inst/ops/overlay.sh" OVERLAY_SOURCE_ONLY=1
	. "$tmp/inst/ops/overlay.sh"
}

# --- insert_panel_tag ------------------------------------------------------------
cat > "$tmp/multi.html" <<'EOF'
<html><head>
<script nonce="{{CSP_NONCE_PLACEHOLDER}}">window.__X=1</script>
<script src="/assets/a.js" type="module"></script>
<script src="/assets/b.js" type="module"></script>
</head></html>
EOF
out=$(load; insert_panel_tag "$tmp/multi.html")
assert_contains "tag goes before the first external script" \
	'<script nonce="{{CSP_NONCE_PLACEHOLDER}}" src="/ops-panel.js"></script><script src="/assets/a.js" type="module">' "$out"
assert_eq "tag inserted once" 1 "$(printf '%s\n' "$out" | grep -o 'ops-panel.js' | grep -c .)"
assert_contains "inline nonce script stays first" '<script nonce="{{CSP_NONCE_PLACEHOLDER}}">window.__X=1</script>' \
	"$(printf '%s\n' "$out" | sed -n 2p)"

printf '<html><script nonce="n">x</script><script src="/assets/a.js" type="module"></script><script src="/assets/b.js"></script></html>\n' > "$tmp/one.html"
out=$(load; insert_panel_tag "$tmp/one.html")
assert_contains "single-line html: before the first external script" \
	'<script nonce="n">x</script><script nonce="{{CSP_NONCE_PLACEHOLDER}}" src="/ops-panel.js"></script><script src="/assets/a.js"' "$out"

printf '<html><script>inline only</script></html>\n' > "$tmp/none.html"
rc=0; (load; insert_panel_tag "$tmp/none.html" > /dev/null) || rc=$?
assert_eq "no external script: exit 3" 3 "$rc"

# --- render_override -------------------------------------------------------------
ops="$tmp/inst/ops"
yaml=$(load; render_override "c.1.js loader.2.js" 0)
assert_eq "marker on line 1" '# generated by ops/overlay.sh - do not edit by hand' "$(printf '%s\n' "$yaml" | head -n 1)"
assert_contains "badge chunk mounted" "      - $ops/patches/c.1.js.br:/srv/app/static/assets/c.1.js.br:ro" "$yaml"
assert_contains "loader mounted" "      - $ops/patches/loader.2.js:/srv/app/static/assets/loader.2.js:ro" "$yaml"
assert_contains "composed index.html mounted" "      - $ops/overlay/index.html.gz:/srv/app/static/index.html.gz:ro" "$yaml"
case "$yaml" in *"edge:"*) fail "badge only: no edge section" ;; *) pass "badge only: no edge section" ;; esac

yaml=$(load; render_override "" 1)
assert_contains "panel: Caddyfile over upstream's" "      - $ops/panel/Caddyfile:/etc/caddy/Caddyfile:ro" "$yaml"
assert_contains "panel: socket dir" "      - $ops/panel/run:/run/fluxer-ops" "$yaml"
assert_contains "panel: script dir" "      - $ops/panel/www:/srv/ops-panel:ro" "$yaml"
case "$yaml" in *"/patches/"*) fail "panel only: no badge mounts" ;; *) pass "panel only: no badge mounts" ;; esac

# --- badge_names -----------------------------------------------------------------
names=$(load; badge_names)
assert_eq "badge off: no names" "" "$names"
printf 'c.js\n' > "$ops/patches/chunk.name"
printf 'c.1.js\nloader.2.js\n' > "$ops/patches/patched.names"
: > "$ops/patches/index.html"
names=$(export DOCKER_RUN_RC=0; load; badge_names)
assert_eq "badge current: its names" "c.1.js loader.2.js " "$names"
err=$( (export DOCKER_RUN_RC=1; load; badge_names > "$tmp/stale.out") 2>&1)
assert_eq "stale badge is left out" "" "$(cat "$tmp/stale.out")"
assert_contains "stale badge is reported" "built for another release" "$err"

# --- ours / apply refusals ---------------------------------------------------------
printf 'services:\n  web: {}\n' > "$tmp/inst/docker-compose.override.yml"
: > "$DOCKER_LOG"
rc=0
err=$(FLUXER_DIR="$tmp/inst" sh "$ops/overlay.sh" apply 2>&1) || rc=$?
assert_eq "foreign override refused" 1 "$rc"
assert_contains "foreign override: says why" "not written by fluxer-ops" "$err"
assert_eq "foreign override untouched" "$(printf 'services:\n  web: {}')" "$(cat "$tmp/inst/docker-compose.override.yml")"
assert_eq "foreign override: docker never called" "" "$(cat "$DOCKER_LOG")"

printf '# generated by ops/badge-patch.sh - do not edit by hand\n' > "$tmp/inst/docker-compose.override.yml"
(load; ours) && pass "legacy badge-patch override counts as ours" || fail "legacy badge-patch override counts as ours"

rm -f "$ops/patches/patched.names"
FLUXER_DIR="$tmp/inst" sh "$ops/overlay.sh" apply > /dev/null
[ ! -e "$tmp/inst/docker-compose.override.yml" ] && pass "nothing on: our override removed" \
	|| fail "nothing on: our override removed"
assert_contains "nothing on: app-proxy and edge recreated stock" "compose up -d --no-deps app-proxy edge" "$(cat "$DOCKER_LOG")"

# --- the composition ----------------------------------------------------------------
reset_state() {
	rm -rf "$ops/patches" "$ops/panel" "$ops/overlay" "$tmp/inst/docker-compose.override.yml"
	mkdir -p "$ops/patches"
	: > "$DOCKER_LOG"
}
badge_state() {
	printf 'c.js\n' > "$ops/patches/chunk.name"
	printf 'c.1.js\nloader.2.js\n' > "$ops/patches/patched.names"
	printf '<html><script nonce="n">badge-repointed</script><script src="/assets/entry.js" type="module"></script><script src="/assets/loader.2.js"></script></html>\n' \
		> "$ops/patches/index.html"
}
panel_state() {
	mkdir -p "$ops/panel/www" "$ops/panel/run"
	# upstream's Caddyfile with the panel's marked block in it, as panel.sh writes it
	printf 'upstream-1\n# >>> fluxer-ops panel (ops/panel.sh)\nroutes\n# <<< fluxer-ops panel\nupstream-2\n' > "$ops/panel/Caddyfile"
	: > "$ops/panel/enabled"
}
printf 'upstream-1\nupstream-2\n' > "$tmp/inst/Caddyfile"
run_overlay() { FLUXER_DIR="$tmp/inst" sh "$ops/overlay.sh" "$@"; }

# stale when a non-patched asset named by the patched index.html is gone from the image
reset_state; badge_state
: > "$DOCKER_LOG"
err=$( (export DOCKER_MISSING=entry.js; load; badge_names > "$tmp/stale.out") 2>&1)
assert_eq "badge with a vanished entry file is stale" "" "$(cat "$tmp/stale.out")"
assert_contains "vanished entry file: reported" "built for another release" "$err"
assert_contains "probe lists the non-patched asset" "entry.js" "$(cat "$DOCKER_LOG")"
assert_contains "probe lists the stock chunk" "c.js" "$(cat "$DOCKER_LOG")"
case "$(cat "$DOCKER_LOG")" in *"c.1.js"*) fail "probe skips patched files" ;; *) pass "probe skips patched files" ;; esac

# (a) badge + panel
reset_state; badge_state; panel_state
run_overlay apply > /dev/null
o=$(cat "$tmp/inst/docker-compose.override.yml")
assert_contains "badge+panel: badge chunk mounted" "$ops/patches/c.1.js:/srv/app/static/assets/c.1.js:ro" "$o"
assert_contains "badge+panel: edge section" "  edge:" "$o"
assert_contains "badge+panel: Caddyfile mounted" "$ops/panel/Caddyfile:/etc/caddy/Caddyfile:ro" "$o"
html=$(cat "$ops/overlay/index.html")
assert_contains "badge+panel: badge's repointed content" "badge-repointed" "$html"
assert_contains "badge+panel: panel tag before the first external script" \
	'<script nonce="{{CSP_NONCE_PLACEHOLDER}}" src="/ops-panel.js"></script><script src="/assets/entry.js"' "$html"
assert_eq "badge+panel: .br written" "$html" "$(cat "$ops/overlay/index.html.br")"
assert_eq "badge+panel: .gz written" "$html" "$(cat "$ops/overlay/index.html.gz")"
assert_contains "badge+panel: services recreated" "compose up -d --no-deps app-proxy edge" "$(cat "$DOCKER_LOG")"

# (b) stale badge + panel
reset_state; badge_state; panel_state
err=$(DOCKER_RUN_RC=1 run_overlay apply 2>&1 > /dev/null)
assert_contains "stale badge + panel: warned" "built for another release" "$err"
o=$(cat "$tmp/inst/docker-compose.override.yml")
case "$o" in *"/patches/"*) fail "stale badge + panel: no patches mounts" ;; *) pass "stale badge + panel: no patches mounts" ;; esac
assert_contains "stale badge + panel: edge section" "  edge:" "$o"
html=$(cat "$ops/overlay/index.html")
assert_contains "stale badge + panel: built from the stock html" "stock-entry.js" "$html"
assert_contains "stale badge + panel: tag before the first external script" \
	'<script nonce="{{CSP_NONCE_PLACEHOLDER}}" src="/ops-panel.js"></script><script src="/assets/stock-entry.js"' "$html"
case "$html" in *badge-repointed*) fail "stale badge + panel: old badge html not used" ;; *) pass "stale badge + panel: old badge html not used" ;; esac

# panel enabled but its files are gone: left out, never mounted
reset_state; badge_state; panel_state
rm -f "$ops/panel/Caddyfile"
err=$(run_overlay apply 2>&1 > /dev/null)
assert_contains "incomplete panel: warned" "incomplete" "$err"
o=$(cat "$tmp/inst/docker-compose.override.yml")
case "$o" in *"edge:"*) fail "incomplete panel: no edge section" ;; *) pass "incomplete panel: no edge section" ;; esac
assert_contains "incomplete panel: badge still served" "$ops/patches/c.1.js:" "$o"
for missing in www run; do
	reset_state; panel_state
	rmdir "$ops/panel/$missing"
	err=$(run_overlay apply 2>&1 > /dev/null)
	assert_contains "panel without $missing/: warned" "incomplete" "$err"
	[ ! -e "$tmp/inst/docker-compose.override.yml" ] && pass "panel without $missing/: no override" \
		|| fail "panel without $missing/: no override"
done

# the panel's Caddyfile copy was built from an older upstream Caddyfile: left out, never mounted
reset_state; badge_state; panel_state
printf 'upstream-1\nupstream-CHANGED\n' > "$tmp/inst/Caddyfile"
err=$(run_overlay apply 2>&1 > /dev/null)
assert_contains "stale panel copy: warned" "built from an older upstream Caddyfile; leaving the panel out (run: fluxer panel refresh)" "$err"
o=$(cat "$tmp/inst/docker-compose.override.yml")
case "$o" in *"edge:"*) fail "stale panel copy: no edge section" ;; *) pass "stale panel copy: no edge section" ;; esac
assert_contains "stale panel copy: badge still served" "$ops/patches/c.1.js:" "$o"
case "$(cat "$ops/overlay/index.html")" in *ops-panel.js*) fail "stale panel copy: no panel tag" ;; *) pass "stale panel copy: no panel tag" ;; esac
printf 'upstream-1\nupstream-2\n' > "$tmp/inst/Caddyfile"
run_overlay apply > /dev/null 2>&1
assert_contains "fresh panel copy: edge section" "  edge:" "$(cat "$tmp/inst/docker-compose.override.yml")"

# (c) suspend
reset_state; badge_state; panel_state
run_overlay apply > /dev/null
: > "$DOCKER_LOG"
run_overlay suspend > /dev/null
[ ! -e "$tmp/inst/docker-compose.override.yml" ] && pass "suspend removes our override" || fail "suspend removes our override"
assert_contains "suspend recreates app-proxy and edge" "compose up -d --no-deps app-proxy edge" "$(cat "$DOCKER_LOG")"
[ -f "$ops/panel/enabled" ] && [ -s "$ops/patches/patched.names" ] && pass "suspend keeps every feature's state" \
	|| fail "suspend keeps every feature's state"
printf 'services:\n  web: {}\n' > "$tmp/inst/docker-compose.override.yml"
: > "$DOCKER_LOG"
run_overlay suspend > /dev/null
assert_eq "suspend leaves a foreign override alone" "$(printf 'services:\n  web: {}')" "$(cat "$tmp/inst/docker-compose.override.yml")"
assert_eq "suspend on a foreign override: docker never called" "" "$(cat "$DOCKER_LOG")"

finish
