#!/bin/sh
# overlay_test.sh - overlay.sh composes the badge patch and the Ops panel into one
# override and one index.html. Stubs only: docker never reaches the real instance.
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
SRC=$(dirname "$HERE")
. "$HERE/assert.sh"
tmp=$(readlink -f "$(mktemp -d)")
trap 'rm -rf "$tmp"' EXIT

mkdir -p "$tmp/inst/ops/patches" "$tmp/stub"
cp "$SRC"/*.sh "$tmp/inst/ops/"
: > "$tmp/inst/docker-compose.yml"
printf 'FLUXER_DOMAIN=chat.example.test\n' > "$tmp/inst/.env"

# docker stub: logs every call; `compose config --images` names an image, `run` exits
# with $DOCKER_RUN_RC (the "is this chunk still in the image" probe).
cat > "$tmp/stub/docker" <<'EOF'
#!/bin/sh
printf '%s\n' "$*" >> "$DOCKER_LOG"
case "$1 $2" in
	"compose config") echo ghcr.io/fluxerapp/fluxer-app-proxy-self-hosted:v1; exit 0 ;;
	"compose up") exit 0 ;;
esac
[ "$1" = run ] && exit "${DOCKER_RUN_RC:-0}"
exit 0
EOF
chmod +x "$tmp/stub/docker"
export DOCKER_LOG="$tmp/docker.log"
: > "$DOCKER_LOG"
PATH="$tmp/stub:$PATH"

load() {
	# shellcheck disable=SC2034 # read by the sourced overlay.sh and lib.sh
	FLUXER_DIR="$tmp/inst" OPS_SELF="$tmp/inst/ops/overlay.sh" OVERLAY_SOURCE_ONLY=1
	. "$tmp/inst/ops/overlay.sh"
}

# --- insert_panel_tag ------------------------------------------------------------
cat > "$tmp/multi.html" <<'EOF'
<html><head>
<script nonce="{{CSP_NONCE_PLACEHOLDER}}">window.__X=1</script>
<script src="/assets/a.js" type="module"></script>
<script src="/assets/b.js" type="module"></script>
</head></html>
EOF
out=$(load; insert_panel_tag "$tmp/multi.html")
assert_contains "tag goes before the first external script" \
	'<script src="/ops-panel.js"></script><script src="/assets/a.js" type="module">' "$out"
assert_eq "tag inserted once" 1 "$(printf '%s\n' "$out" | grep -o 'ops-panel.js' | grep -c .)"
assert_contains "inline nonce script stays first" '<script nonce="{{CSP_NONCE_PLACEHOLDER}}">window.__X=1</script>' \
	"$(printf '%s\n' "$out" | sed -n 2p)"

printf '<html><script nonce="n">x</script><script src="/assets/a.js" type="module"></script><script src="/assets/b.js"></script></html>\n' > "$tmp/one.html"
out=$(load; insert_panel_tag "$tmp/one.html")
assert_contains "single-line html: before the first external script" \
	'<script nonce="n">x</script><script src="/ops-panel.js"></script><script src="/assets/a.js"' "$out"

printf '<html><script>inline only</script></html>\n' > "$tmp/none.html"
rc=0; (load; insert_panel_tag "$tmp/none.html" > /dev/null) || rc=$?
assert_eq "no external script: exit 3" 3 "$rc"

# --- render_override -------------------------------------------------------------
ops="$tmp/inst/ops"
yaml=$(load; render_override "c.1.js loader.2.js" 0)
assert_eq "marker on line 1" '# generated by ops/overlay.sh - do not edit by hand' "$(printf '%s\n' "$yaml" | head -n 1)"
assert_contains "badge chunk mounted" "      - $ops/patches/c.1.js.br:/srv/app/static/assets/c.1.js.br:ro" "$yaml"
assert_contains "loader mounted" "      - $ops/patches/loader.2.js:/srv/app/static/assets/loader.2.js:ro" "$yaml"
assert_contains "composed index.html mounted" "      - $ops/overlay/index.html.gz:/srv/app/static/index.html.gz:ro" "$yaml"
case "$yaml" in *"edge:"*) fail "badge only: no edge section" ;; *) pass "badge only: no edge section" ;; esac

yaml=$(load; render_override "" 1)
assert_contains "panel: Caddyfile over upstream's" "      - $ops/panel/Caddyfile:/etc/caddy/Caddyfile:ro" "$yaml"
assert_contains "panel: socket dir" "      - $ops/panel/run:/run/fluxer-ops" "$yaml"
assert_contains "panel: script dir" "      - $ops/panel/www:/srv/ops-panel:ro" "$yaml"
case "$yaml" in *"/patches/"*) fail "panel only: no badge mounts" ;; *) pass "panel only: no badge mounts" ;; esac

# --- badge_names -----------------------------------------------------------------
names=$(load; badge_names)
assert_eq "badge off: no names" "" "$names"
printf 'c.js\n' > "$ops/patches/chunk.name"
printf 'c.1.js\nloader.2.js\n' > "$ops/patches/patched.names"
: > "$ops/patches/index.html"
names=$(export DOCKER_RUN_RC=0; load; badge_names)
assert_eq "badge current: its names" "c.1.js loader.2.js " "$names"
err=$( (export DOCKER_RUN_RC=1; load; badge_names > "$tmp/stale.out") 2>&1)
assert_eq "stale badge is left out" "" "$(cat "$tmp/stale.out")"
assert_contains "stale badge is reported" "built for another release" "$err"

# --- ours / apply refusals ---------------------------------------------------------
printf 'services:\n  web: {}\n' > "$tmp/inst/docker-compose.override.yml"
: > "$DOCKER_LOG"
rc=0
err=$(FLUXER_DIR="$tmp/inst" sh "$ops/overlay.sh" apply 2>&1) || rc=$?
assert_eq "foreign override refused" 1 "$rc"
assert_contains "foreign override: says why" "not written by fluxer-ops" "$err"
assert_eq "foreign override untouched" "$(printf 'services:\n  web: {}')" "$(cat "$tmp/inst/docker-compose.override.yml")"
assert_eq "foreign override: docker never called" "" "$(cat "$DOCKER_LOG")"

printf '# generated by ops/badge-patch.sh - do not edit by hand\n' > "$tmp/inst/docker-compose.override.yml"
(load; ours) && pass "legacy badge-patch override counts as ours" || fail "legacy badge-patch override counts as ours"

rm -f "$ops/patches/patched.names"
FLUXER_DIR="$tmp/inst" sh "$ops/overlay.sh" apply > /dev/null
[ ! -e "$tmp/inst/docker-compose.override.yml" ] && pass "nothing on: our override removed" \
	|| fail "nothing on: our override removed"
assert_contains "nothing on: app-proxy and edge recreated stock" "compose up -d app-proxy edge" "$(cat "$DOCKER_LOG")"

finish
